import {AppConsts} from '@shared/AppConsts';
import { Component, Injector, ViewEncapsulation, ViewChild } from '@angular/core';
import { ActivatedRoute , Router} from '@angular/router';
import { SycSegmentIdentifierDefinitionsServiceProxy, SycSegmentIdentifierDefinitionDto  } from '@shared/service-proxies/service-proxies';
import { NotifyService } from 'abp-ng2-module';
import { AppComponentBase } from '@shared/common/app-component-base';
import { TokenAuthServiceProxy } from '@shared/service-proxies/service-proxies';
import { CreateOrEditSycSegmentIdentifierDefinitionModalComponent } from './create-or-edit-sycSegmentIdentifierDefinition-modal.component';

import { ViewSycSegmentIdentifierDefinitionModalComponent } from './view-sycSegmentIdentifierDefinition-modal.component';
import { appModuleAnimation } from '@shared/animations/routerTransition';
import { Table } from 'primeng/table';
import { Paginator } from 'primeng/paginator';
import { LazyLoadEvent } from 'primeng/public_api';
import { FileDownloadService } from '@shared/utils/file-download.service';
import { EntityTypeHistoryModalComponent } from '@app/shared/common/entityHistory/entity-type-history-modal.component';
import * as _ from 'lodash';
import * as moment from 'moment';


@Component({
    templateUrl: './sycSegmentIdentifierDefinitions.component.html',
    encapsulation: ViewEncapsulation.None,
    animations: [appModuleAnimation()]
})
export class SycSegmentIdentifierDefinitionsComponent extends AppComponentBase {
    
    
    @ViewChild('entityTypeHistoryModal', { static: true }) entityTypeHistoryModal: EntityTypeHistoryModalComponent;
    @ViewChild('createOrEditSycSegmentIdentifierDefinitionModal', { static: true }) createOrEditSycSegmentIdentifierDefinitionModal: CreateOrEditSycSegmentIdentifierDefinitionModalComponent;
    @ViewChild('viewSycSegmentIdentifierDefinitionModalComponent', { static: true }) viewSycSegmentIdentifierDefinitionModal: ViewSycSegmentIdentifierDefinitionModalComponent;   
    
    @ViewChild('dataTable', { static: true }) dataTable: Table;
    @ViewChild('paginator', { static: true }) paginator: Paginator;

    advancedFiltersAreShown = false;
    filterText = '';
    codeFilter = '';
    nameFilter = '';
    maxSegmentNumberFilter : number;
		maxSegmentNumberFilterEmpty : number;
		minSegmentNumberFilter : number;
		minSegmentNumberFilterEmpty : number;
    segmentHeaderFilter = '';
    segmentMaskFilter = '';
    maxSegmentLengthFilter : number;
		maxSegmentLengthFilterEmpty : number;
		minSegmentLengthFilter : number;
		minSegmentLengthFilterEmpty : number;
    segmentTypeFilter = '';
    isAutoGeneratedFilter = -1;
    isEditableFilter = -1;
    isVisibleFilter = -1;
    maxCodeStartingValueFilter : number;
		maxCodeStartingValueFilterEmpty : number;
		minCodeStartingValueFilter : number;
		minCodeStartingValueFilterEmpty : number;
    lookOrFieldNameFilter = '';
        sycIdentifierDefinitionCodeFilter = '';


    _entityTypeFullName = 'onetouch.SycSegmentIdentifierDefinitions.SycSegmentIdentifierDefinition';
    entityHistoryEnabled = false;



    constructor(
        injector: Injector,
        private _sycSegmentIdentifierDefinitionsServiceProxy: SycSegmentIdentifierDefinitionsServiceProxy,
        private _notifyService: NotifyService,
        private _tokenAuth: TokenAuthServiceProxy,
        private _activatedRoute: ActivatedRoute,
        private _fileDownloadService: FileDownloadService
    ) {
        super(injector);
    }

    ngOnInit(): void {
        this.entityHistoryEnabled = this.setIsEntityHistoryEnabled();
    }

    private setIsEntityHistoryEnabled(): boolean {
        let customSettings = (abp as any).custom;
        return this.isGrantedAny('Pages.Administration.AuditLogs') && customSettings.EntityHistory && customSettings.EntityHistory.isEnabled && _.filter(customSettings.EntityHistory.enabledEntities, entityType => entityType === this._entityTypeFullName).length === 1;
    }

    getSycSegmentIdentifierDefinitions(event?: LazyLoadEvent) {
        if (this.primengTableHelper.shouldResetPaging(event)) {
            this.paginator.changePage(0);
            return;
        }

        this.primengTableHelper.showLoadingIndicator();

        this._sycSegmentIdentifierDefinitionsServiceProxy.getAll(
            this.filterText,
            this.codeFilter,
            this.nameFilter,
            this.maxSegmentNumberFilter == null ? this.maxSegmentNumberFilterEmpty: this.maxSegmentNumberFilter,
            this.minSegmentNumberFilter == null ? this.minSegmentNumberFilterEmpty: this.minSegmentNumberFilter,
            this.segmentHeaderFilter,
            this.segmentMaskFilter,
            this.maxSegmentLengthFilter == null ? this.maxSegmentLengthFilterEmpty: this.maxSegmentLengthFilter,
            this.minSegmentLengthFilter == null ? this.minSegmentLengthFilterEmpty: this.minSegmentLengthFilter,
            this.segmentTypeFilter,
            this.isAutoGeneratedFilter,
            this.isEditableFilter,
            this.isVisibleFilter,
            this.maxCodeStartingValueFilter == null ? this.maxCodeStartingValueFilterEmpty: this.maxCodeStartingValueFilter,
            this.minCodeStartingValueFilter == null ? this.minCodeStartingValueFilterEmpty: this.minCodeStartingValueFilter,
            this.lookOrFieldNameFilter,
            this.sycIdentifierDefinitionCodeFilter,
            this.primengTableHelper.getSorting(this.dataTable),
            this.primengTableHelper.getSkipCount(this.paginator, event),
            this.primengTableHelper.getMaxResultCount(this.paginator, event)
        ).subscribe(result => {
            this.primengTableHelper.totalRecordsCount = result.totalCount;
            this.primengTableHelper.records = result.items;
            this.primengTableHelper.hideLoadingIndicator();
        });
    }

    reloadPage(): void {
        this.paginator.changePage(this.paginator.getPage());
    }

    createSycSegmentIdentifierDefinition(): void {
        this.createOrEditSycSegmentIdentifierDefinitionModal.show();        
    }


    showHistory(sycSegmentIdentifierDefinition: SycSegmentIdentifierDefinitionDto): void {
        this.entityTypeHistoryModal.show({
            entityId: sycSegmentIdentifierDefinition.id.toString(),
            entityTypeFullName: this._entityTypeFullName,
            entityTypeDescription: ''
        });
    }

    deleteSycSegmentIdentifierDefinition(sycSegmentIdentifierDefinition: SycSegmentIdentifierDefinitionDto): void {
        this.message.confirm(
            '',
            this.l('AreYouSure'),
            (isConfirmed) => {
                if (isConfirmed) {
                    this._sycSegmentIdentifierDefinitionsServiceProxy.delete(sycSegmentIdentifierDefinition.id)
                        .subscribe(() => {
                            this.reloadPage();
                            this.notify.success(this.l('SuccessfullyDeleted'));
                        });
                }
            }
        );
    }

    exportToExcel(): void {
        this._sycSegmentIdentifierDefinitionsServiceProxy.getSycSegmentIdentifierDefinitionsToExcel(
        this.filterText,
            this.codeFilter,
            this.nameFilter,
            this.maxSegmentNumberFilter == null ? this.maxSegmentNumberFilterEmpty: this.maxSegmentNumberFilter,
            this.minSegmentNumberFilter == null ? this.minSegmentNumberFilterEmpty: this.minSegmentNumberFilter,
            this.segmentHeaderFilter,
            this.segmentMaskFilter,
            this.maxSegmentLengthFilter == null ? this.maxSegmentLengthFilterEmpty: this.maxSegmentLengthFilter,
            this.minSegmentLengthFilter == null ? this.minSegmentLengthFilterEmpty: this.minSegmentLengthFilter,
            this.segmentTypeFilter,
            this.isAutoGeneratedFilter,
            this.isEditableFilter,
            this.isVisibleFilter,
            this.maxCodeStartingValueFilter == null ? this.maxCodeStartingValueFilterEmpty: this.maxCodeStartingValueFilter,
            this.minCodeStartingValueFilter == null ? this.minCodeStartingValueFilterEmpty: this.minCodeStartingValueFilter,
            this.lookOrFieldNameFilter,
            this.sycIdentifierDefinitionCodeFilter,
        )
        .subscribe(result => {
            this._fileDownloadService.downloadTempFile(result);
         });
    }
    
    
    
    
    
}
