//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onetouch.Web.PredefinedReports.ProductCatalog {
    
    public partial class Color_variations : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "onetouch.Web.PredefinedReports.ProductCatalog.Color_variations.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.xrPictureBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("xrPictureBox1");
            this.label6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label6");
            this.label5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label5");
            this.label7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label7");

            // Parameters
            this.ItemId = reportInitializer.GetParameter("ItemId");
            this.ItemCode = reportInitializer.GetParameter("ItemCode");
            this.ItemName = reportInitializer.GetParameter("ItemName");
            this.ItemDesc = reportInitializer.GetParameter("ItemDesc");
            this.productListId = reportInitializer.GetParameter("productListId");
            this.attachmentBaseUrl2 = reportInitializer.GetParameter("attachmentBaseUrl2");
            this.tenantId2 = reportInitializer.GetParameter("tenantId2");
            this.showNo = reportInitializer.GetParameter("showNo");
            this.itemlistid = reportInitializer.GetParameter("itemlistid");
            this.mimimumInStockQty = reportInitializer.GetParameter("mimimumInStockQty");
            this.onlyInStockColors = reportInitializer.GetParameter("onlyInStockColors");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");

            // Styles
            this.Title = reportInitializer.GetStyle("Title");
            this.DetailCaption1 = reportInitializer.GetStyle("DetailCaption1");
            this.DetailData1 = reportInitializer.GetStyle("DetailData1");
            this.DetailData3_Odd = reportInitializer.GetStyle("DetailData3_Odd");
            this.PageInfo = reportInitializer.GetStyle("PageInfo");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRPictureBox xrPictureBox1;
        private DevExpress.XtraReports.UI.XRLabel label6;
        private DevExpress.XtraReports.UI.XRLabel label5;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.XRControlStyle Title;
        private DevExpress.XtraReports.UI.XRControlStyle DetailCaption1;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData1;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData3_Odd;
        private DevExpress.XtraReports.UI.XRControlStyle PageInfo;
        private DevExpress.XtraReports.Parameters.Parameter ItemId;
        private DevExpress.XtraReports.Parameters.Parameter ItemCode;
        private DevExpress.XtraReports.Parameters.Parameter ItemName;
        private DevExpress.XtraReports.Parameters.Parameter ItemDesc;
        private DevExpress.XtraReports.Parameters.Parameter productListId;
        private DevExpress.XtraReports.Parameters.Parameter attachmentBaseUrl2;
        private DevExpress.XtraReports.Parameters.Parameter tenantId2;
        private DevExpress.XtraReports.Parameters.Parameter showNo;
        private DevExpress.XtraReports.Parameters.Parameter itemlistid;
        private DevExpress.XtraReports.Parameters.Parameter mimimumInStockQty;
        private DevExpress.XtraReports.Parameters.Parameter onlyInStockColors;
        private DevExpress.XtraReports.UI.XRLabel label7;
    }
}
