//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onetouch.Web.PredefinedReports.ProductCatalog {
    
    public partial class CoverPage_P : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "onetouch.Web.PredefinedReports.ProductCatalog.CoverPage_P.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.label16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label16");
            this.label15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label15");
            this.label14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label14");
            this.xrShape1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape1");
            this.pageInfo3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo3");
            this.pictureBox3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox3");
            this.xrLabel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel1");
            this.label9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label9");
            this.label13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label13");

            // Parameters
            this.address = reportInitializer.GetParameter("address");
            this.BKGround = reportInitializer.GetParameter("BKGround");
            this.logo = reportInitializer.GetParameter("logo");
            this.telephone = reportInitializer.GetParameter("telephone");
            this.email = reportInitializer.GetParameter("email");
            this.tenantName = reportInitializer.GetParameter("tenantName");
            this.accountName = reportInitializer.GetParameter("accountName");
            this.reportTitle = reportInitializer.GetParameter("reportTitle");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.XRLabel label16;
        private DevExpress.XtraReports.UI.XRLabel label15;
        private DevExpress.XtraReports.UI.XRLabel label14;
        private DevExpress.XtraReports.UI.XRShape xrShape1;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo3;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox3;
        private DevExpress.XtraReports.UI.XRLabel xrLabel1;
        private DevExpress.XtraReports.UI.XRLabel label9;
        private DevExpress.XtraReports.UI.XRLabel label13;
        private DevExpress.XtraReports.Parameters.Parameter address;
        private DevExpress.XtraReports.Parameters.Parameter BKGround;
        private DevExpress.XtraReports.Parameters.Parameter logo;
        private DevExpress.XtraReports.Parameters.Parameter telephone;
        private DevExpress.XtraReports.Parameters.Parameter email;
        private DevExpress.XtraReports.Parameters.Parameter tenantName;
        private DevExpress.XtraReports.Parameters.Parameter accountName;
        private DevExpress.XtraReports.Parameters.Parameter reportTitle;
    }
}
