//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onetouch.Web.PredefinedReports.ProductCatalog {
    
    public partial class ProductsCatalogTemplate5 : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "onetouch.Web.PredefinedReports.ProductCatalog.ProductsCatalogTemplate5.vsrepx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.VerticalDetail = reportInitializer.GetControl<DevExpress.XtraReports.UI.VerticalDetailBand>("VerticalDetail");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.SubBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("SubBand1");
            this.SubBand2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("SubBand2");
            this.subreport4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("subreport4");
            this.subreport4.ReportSource = new onetouch.Web.PredefinedReports.ProductCatalog.CoverPage();
            this.subreport2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("subreport2");
            this.subreport2.ReportSource = new onetouch.Web.PredefinedReports.ProductCatalog.Colors();
            this.pictureBox3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox3");
            this.label9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label9");
            this.label13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label13");
            this.pageInfo3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo3");
            this.subreport1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("subreport1");
            this.subreport1.ReportSource = new onetouch.Web.PredefinedReports.ProductCatalog.Color_Size();
            this.panel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("panel1");
            this.xrLabel3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel3");
            this.label7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label7");
            this.label8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label8");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.pictureBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox1");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label11");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.label6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label6");
            this.label5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label5");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");

            // Parameters
            this.to = reportInitializer.GetParameter("to");
            this.BKGround = reportInitializer.GetParameter("BKGround");
            this.cc = reportInitializer.GetParameter("cc");
            this.bcc = reportInitializer.GetParameter("bcc");
            this.subject = reportInitializer.GetParameter("subject");
            this.body = reportInitializer.GetParameter("body");
            this.showCover = reportInitializer.GetParameter("showCover");
            this.ColorPageSort = reportInitializer.GetParameter("ColorPageSort");
            this.DetailPageSort = reportInitializer.GetParameter("DetailPageSort");
            this.DetailPageShowCategory = reportInitializer.GetParameter("DetailPageShowCategory");
            this.ColorPageShowCategory = reportInitializer.GetParameter("ColorPageShowCategory");
            this.PrintLinesheet = reportInitializer.GetParameter("PrintLinesheet");
            this.EmailLinesheet = reportInitializer.GetParameter("EmailLinesheet");
            this.showColors = reportInitializer.GetParameter("showColors");
            this.showCode = reportInitializer.GetParameter("showCode");
            this.showQty = reportInitializer.GetParameter("showQty");
            this.showNo = reportInitializer.GetParameter("showNo");
            this.showPrice = reportInitializer.GetParameter("showPrice");
            this.showFooter = reportInitializer.GetParameter("showFooter");
            this.showSpecialPrice = reportInitializer.GetParameter("showSpecialPrice");
            this.specialPriceLevel = reportInitializer.GetParameter("specialPriceLevel");
            this.orderBy = reportInitializer.GetParameter("orderBy");
            this.reportTitle = reportInitializer.GetParameter("reportTitle");
            this.tenantId = reportInitializer.GetParameter("tenantId");
            this.userId = reportInitializer.GetParameter("userId");
            this.itemsListId = reportInitializer.GetParameter("itemsListId");
            this.preparedForContactId = reportInitializer.GetParameter("preparedForContactId");
            this.selectedKey = reportInitializer.GetParameter("selectedKey");
            this.attachmentBaseUrl = reportInitializer.GetParameter("attachmentBaseUrl");
            this.attributeTypeId = reportInitializer.GetParameter("attributeTypeId");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");

            // Styles
            this.Title = reportInitializer.GetStyle("Title");
            this.DetailCaption1 = reportInitializer.GetStyle("DetailCaption1");
            this.DetailData1 = reportInitializer.GetStyle("DetailData1");
            this.DetailData3_Odd = reportInitializer.GetStyle("DetailData3_Odd");
            this.PageInfo = reportInitializer.GetStyle("PageInfo");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.VerticalDetailBand VerticalDetail;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.SubBand SubBand1;
        private DevExpress.XtraReports.UI.SubBand SubBand2;
        private DevExpress.XtraReports.UI.XRSubreport subreport4;
        private DevExpress.XtraReports.UI.XRSubreport subreport2;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox3;
        private DevExpress.XtraReports.UI.XRLabel label9;
        private DevExpress.XtraReports.UI.XRLabel label13;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo3;
        private DevExpress.XtraReports.UI.XRSubreport subreport1;
        private DevExpress.XtraReports.UI.XRPanel panel1;
        private DevExpress.XtraReports.UI.XRLabel xrLabel3;
        private DevExpress.XtraReports.UI.XRLabel label7;
        private DevExpress.XtraReports.UI.XRLabel label8;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox1;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label11;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRLabel label6;
        private DevExpress.XtraReports.UI.XRLabel label5;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.XRControlStyle Title;
        private DevExpress.XtraReports.UI.XRControlStyle DetailCaption1;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData1;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData3_Odd;
        private DevExpress.XtraReports.UI.XRControlStyle PageInfo;
        private DevExpress.XtraReports.Parameters.Parameter to;
        private DevExpress.XtraReports.Parameters.Parameter BKGround;
        private DevExpress.XtraReports.Parameters.Parameter cc;
        private DevExpress.XtraReports.Parameters.Parameter bcc;
        private DevExpress.XtraReports.Parameters.Parameter subject;
        private DevExpress.XtraReports.Parameters.Parameter body;
        private DevExpress.XtraReports.Parameters.Parameter showCover;
        private DevExpress.XtraReports.Parameters.Parameter ColorPageSort;
        private DevExpress.XtraReports.Parameters.Parameter DetailPageSort;
        private DevExpress.XtraReports.Parameters.Parameter DetailPageShowCategory;
        private DevExpress.XtraReports.Parameters.Parameter ColorPageShowCategory;
        private DevExpress.XtraReports.Parameters.Parameter PrintLinesheet;
        private DevExpress.XtraReports.Parameters.Parameter EmailLinesheet;
        private DevExpress.XtraReports.Parameters.Parameter showColors;
        private DevExpress.XtraReports.Parameters.Parameter showCode;
        private DevExpress.XtraReports.Parameters.Parameter showQty;
        private DevExpress.XtraReports.Parameters.Parameter showNo;
        private DevExpress.XtraReports.Parameters.Parameter showPrice;
        private DevExpress.XtraReports.Parameters.Parameter showFooter;
        private DevExpress.XtraReports.Parameters.Parameter showSpecialPrice;
        private DevExpress.XtraReports.Parameters.Parameter specialPriceLevel;
        private DevExpress.XtraReports.Parameters.Parameter orderBy;
        private DevExpress.XtraReports.Parameters.Parameter reportTitle;
        private DevExpress.XtraReports.Parameters.Parameter tenantId;
        private DevExpress.XtraReports.Parameters.Parameter userId;
        private DevExpress.XtraReports.Parameters.Parameter itemsListId;
        private DevExpress.XtraReports.Parameters.Parameter preparedForContactId;
        private DevExpress.XtraReports.Parameters.Parameter selectedKey;
        private DevExpress.XtraReports.Parameters.Parameter attachmentBaseUrl;
        private DevExpress.XtraReports.Parameters.Parameter attributeTypeId;
    }
}
