using Abp.Application.Services.Dto;
using System;

namespace onetouch.SycSegmentIdentifierDefinitions.Dtos
{
    public class GetAllSycSegmentIdentifierDefinitionsInput : PagedAndSortedResultRequestDto
    {
        public string Filter { get; set; }

        public string CodeFilter { get; set; }

        public string NameFilter { get; set; }

        public int? MaxSegmentNumberFilter { get; set; }
        public int? MinSegmentNumberFilter { get; set; }

        public string SegmentHeaderFilter { get; set; }

        public string SegmentMaskFilter { get; set; }

        public int? MaxSegmentLengthFilter { get; set; }
        public int? MinSegmentLengthFilter { get; set; }

        public string SegmentTypeFilter { get; set; }

        public int? IsAutoGeneratedFilter { get; set; }

        public int? IsEditableFilter { get; set; }

        public int? IsVisibleFilter { get; set; }

        public int? MaxCodeStartingValueFilter { get; set; }
        public int? MinCodeStartingValueFilter { get; set; }

        public string LookOrFieldNameFilter { get; set; }

        public string SycIdentifierDefinitionCodeFilter { get; set; }

    }
}