using System;
using Abp.Application.Services.Dto;

namespace onetouch.SycSegmentIdentifierDefinitions.Dtos
{
    public class SycSegmentIdentifierDefinitionDto : EntityDto<long>
    {
        public string Code { get; set; }

        public string Name { get; set; }

        public int SegmentNumber { get; set; }

        public string SegmentHeader { get; set; }

        public string SegmentMask { get; set; }

        public int SegmentLength { get; set; }

        public string SegmentType { get; set; }

        public bool IsAutoGenerated { get; set; }

        public bool IsEditable { get; set; }

        public bool IsVisible { get; set; }

        public int CodeStartingValue { get; set; }

        public string LookOrFieldName { get; set; }

        public long? SycIdentifierDefinitionId { get; set; }

    }
}