using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace onetouch.Migrations
{
    /// <inheritdoc />
    public partial class updatelinesheet : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(" CREATE OR ALTER VIEW [dbo].[vw_variation_sock]  \r\nAS\r\nSELECT     distinct    AppItems.Id as   AppItemId, AppItems.ParentId, a.EntityId, a.EntityCode, a.AttributeCode, a.AttributeValue, b.AttributeValue AS AttributeValue2,\r\n\t\t\tISNULL(AppItems.StockAvailability, 0) AS StockAvailability, a.AttributeId, AppEntityAttachments.AttachmentId, \r\n                         CAST(ISNULL(AppAttachments.TenantId, - 1) AS nvarchar(50)) + '/' + AppAttachments.Attachment AS Attachment,\r\n                             (SELECT       convert(varchar,  cast(c.AttributeValue as date) ,1) as AttributeValue3\r\n                               FROM            AppEntityExtraData AS c\r\n                               WHERE        (appitems.ParentEntityId = EntityId) AND (AttributeId = 660)) AS AttributeValue3\r\n\t\t\t\t\t\t\t     \r\n\t\t\t\t\t\t\t\t,(Select top(1) id from \r\nAppItemSizeScalesDetails\r\nwhere isdeleted = 0 and SizeCode = b.AttributeCode and SizeScaleId in\r\n(select id from AppItemSizeScalesHeader where isdeleted = 0 and AppItemSizeScalesHeader.AppItemId = AppItems.ParentId and \r\nAppItemSizeScalesHeader.ParentId is null)) as id \r\n\t\t\t\t\t\t\t\t \r\nFROM            AppEntityExtraData AS a INNER JOIN\r\n                         AppEntityExtraData AS b ON a.EntityId = b.EntityId LEFT OUTER JOIN\r\n                         AppEntityExtraData AS c ON a.EntityId = c.EntityId LEFT OUTER JOIN\r\n                         AppItems ON AppItems.EntityId = a.EntityId LEFT OUTER JOIN\r\n                         AppEntityAttachments ON (\r\n\t\t\t\t\t\t not (a.AttributeValueId is null) and (AppEntityAttachments.EntityId = a.AttributeValueId))\r\n\t\t\t\t\t\t or (a.AttributeValueId is null and AppEntityAttachments.EntityId in (SELECT        TOP (1) Id \r\nFROM            AppEntities\r\nWHERE        (Code = a.AttributeCode) AND (TenantId = AppItems.TenantId OR\r\n                         TenantId IS NULL OR\r\n                         TenantId = - 1))\r\n\t\t\t\t\t\t ) LEFT OUTER JOIN\r\n                         AppAttachments ON AppAttachments.Id = AppEntityAttachments.AttachmentId\r\n\t\t\t\t\t\t  \r\nWHERE        (a.EntityObjectTypeId = (Select TOP(1) ID from SycEntityObjectTypes Where Code='COLOR' COLLATE Latin1_General_CS_AS)) AND\r\n(b.EntityObjectTypeId = (Select TOP(1) ID from SycEntityObjectTypes Where Code='SIZE' COLLATE Latin1_General_CS_AS))  \r\nand AppItems.isdeleted=0 \r\nGO\r\n\r\n");

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(" CREATE OR ALTER VIEW [dbo].[vw_variation_sock]  \r\nAS\r\nSELECT     distinct    AppItems.Id as   AppItemId, AppItems.ParentId, a.EntityId, a.EntityCode, a.AttributeCode, a.AttributeValue, b.AttributeValue AS AttributeValue2,\r\n\t\t\tISNULL(AppItems.StockAvailability, 0) AS StockAvailability, a.AttributeId, AppEntityAttachments.AttachmentId, \r\n                         CAST(ISNULL(AppAttachments.TenantId, - 1) AS nvarchar(50)) + '/' + AppAttachments.Attachment AS Attachment,\r\n                             (SELECT       convert(varchar,  cast(c.AttributeValue as date) ,1) as AttributeValue3\r\n                               FROM            AppEntityExtraData AS c\r\n                               WHERE        (appitems.ParentEntityId = EntityId) AND (AttributeId = 660)) AS AttributeValue3\r\n\t\t\t\t\t\t\t   ,AppItemSizeScalesDetails.Id  \r\nFROM            AppEntityExtraData AS a INNER JOIN\r\n                         AppEntityExtraData AS b ON a.EntityId = b.EntityId LEFT OUTER JOIN\r\n                         AppEntityExtraData AS c ON a.EntityId = c.EntityId LEFT OUTER JOIN\r\n                         AppItems ON AppItems.EntityId = a.EntityId LEFT OUTER JOIN\r\n                         AppEntityAttachments ON AppEntityAttachments.EntityId = a.AttributeValueId LEFT OUTER JOIN\r\n                         AppAttachments ON AppAttachments.Id = AppEntityAttachments.AttachmentId\r\n\t\t\t\t\t\t LEFT OUTER JOIN AppItemSizeScalesHeader on AppItemSizeScalesHeader.AppItemId = AppItems.ParentId\r\n\t\t\t\t\t\t LEFT OUTER JOIN AppItemSizeScalesDetails on AppItemSizeScalesDetails.SizeScaleId = AppItemSizeScalesHeader.Id and AppItemSizeScalesDetails.SizeCode = b.AttributeCode\r\nWHERE        (a.EntityObjectTypeId = (Select TOP(1) ID from SycEntityObjectTypes Where Code='COLOR' COLLATE Latin1_General_CS_AS)) AND (b.EntityObjectTypeId = (Select TOP(1) ID from SycEntityObjectTypes Where Code='SIZE' COLLATE Latin1_General_CS_AS)) and (AppItemSizeScalesHeader.ParentId is null)\r\nand AppItems.isdeleted=0 and AppItemSizeScalesHeader.isdeleted=0 and AppItemSizeScalesDetails.isdeleted=0 \r\n  \r\nGO\r\n");
        }
    }
}
