import { Component, OnInit, EventEmitter, Input, Injector, Output } from '@angular/core';
import { AppComponentBase } from '@shared/common/app-component-base';
import {
  SycIdentifierDefinitionDto,
  GetSycIdentifierDefinitionForViewDto,
  SycSegmentIdentifierDefinitionDto,
  SycIdentifierDefinitionsServiceProxy,
} from '@shared/service-proxies/service-proxies';
import { Observable } from 'rxjs';
import { shareReplay } from 'rxjs/operators';

@Component({
  selector: 'app-codes',
  templateUrl: './codes.component.html',
  styleUrls: ['./codes.component.scss']
})
export class CodesComponent extends AppComponentBase implements OnInit {

  private static definitionRequests: {
    [key: string]: Observable<GetSycIdentifierDefinitionForViewDto>
  } = {};

  sycIdentifierDefinition: SycIdentifierDefinitionDto = new SycIdentifierDefinitionDto();
  getSycIdentifierDefinitionForViewDto: GetSycIdentifierDefinitionForViewDto = new GetSycIdentifierDefinitionForViewDto();
  sycSegmentIdentifierDefinitionDto: SycSegmentIdentifierDefinitionDto = new SycSegmentIdentifierDefinitionDto();

  @Input() placeHolder: string = "";
  @Input() code: string = "";
  @Input() editMode: boolean = false;
  @Input() objectType: string = "";
  @Output() getCodeValue = new EventEmitter<string>();
  @Input() label: string = "";
  @Input() styles;
  @Input() readonly: boolean = false;
  @Input() classes: string = "";
  @Input() maxlength = 6;

  constructor(
    injector: Injector,
    private _sycIdentifierDefinitionsServiceProxy: SycIdentifierDefinitionsServiceProxy,
  ) {
    super(injector);
  }

  ngOnInit(): void {

    if (!this.editMode && !this.code) this.code = '';

    if (!CodesComponent.definitionRequests[this.objectType]) {
      CodesComponent.definitionRequests[this.objectType] =
        this._sycIdentifierDefinitionsServiceProxy
          .getSycIdentifierDefinitionByTypeForView(this.objectType)
          .pipe(shareReplay(1));
    }

    CodesComponent.definitionRequests[this.objectType]
      .subscribe(result => {

        this.sycIdentifierDefinition = result.sycIdentifierDefinition;
        this.getSycIdentifierDefinitionForViewDto = result;

        if (result?.sycSegmentIdentifierDefinitions?.length) {

          this.sycSegmentIdentifierDefinitionDto =
            result.sycSegmentIdentifierDefinitions[0];

          if (!this.editMode &&
              this.sycSegmentIdentifierDefinitionDto.isAutoGenerated &&
              !this.code) {

            this._sycIdentifierDefinitionsServiceProxy
              .getNextEntityCode(this.objectType, this.appSession.tenantId)
              .subscribe(res => {
                this.code = res;
                this.getCodeValue.emit(this.code);
              });
          }
        }
      });
  }

  OnGetCodeValue(nameInput: any) {
    this.code = nameInput.target.value.toUpperCase();
    this.getCodeValue.emit(this.code);
  }
}
