using onetouch.SycIdentifierDefinitions;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Abp.Domain.Entities.Auditing;
using Abp.Domain.Entities;
using Abp.Auditing;

namespace onetouch.SycSegmentIdentifierDefinitions
{
    [Table("SycSegmentIdentifierDefinitions")]
    [Audited]
    public class SycSegmentIdentifierDefinition : FullAuditedEntity<long>, IMayHaveTenant
    {
        public int? TenantId { get; set; }

        [StringLength(SycSegmentIdentifierDefinitionConsts.MaxCodeLength, MinimumLength = SycSegmentIdentifierDefinitionConsts.MinCodeLength)]
        public virtual string Code { get; set; }

        [StringLength(SycSegmentIdentifierDefinitionConsts.MaxNameLength, MinimumLength = SycSegmentIdentifierDefinitionConsts.MinNameLength)]
        public virtual string Name { get; set; }

        public virtual int SegmentNumber { get; set; }

        [StringLength(SycSegmentIdentifierDefinitionConsts.MaxSegmentHeaderLength, MinimumLength = SycSegmentIdentifierDefinitionConsts.MinSegmentHeaderLength)]
        public virtual string SegmentHeader { get; set; }

        [StringLength(SycSegmentIdentifierDefinitionConsts.MaxSegmentMaskLength, MinimumLength = SycSegmentIdentifierDefinitionConsts.MinSegmentMaskLength)]
        public virtual string SegmentMask { get; set; }

        public virtual int SegmentLength { get; set; }

        public virtual string SegmentType { get; set; }

        public virtual bool IsAutoGenerated { get; set; }

        public virtual bool IsEditable { get; set; }

        public virtual bool IsVisible { get; set; }

        public virtual int CodeStartingValue { get; set; }

        [StringLength(SycSegmentIdentifierDefinitionConsts.MaxLookOrFieldNameLength, MinimumLength = SycSegmentIdentifierDefinitionConsts.MinLookOrFieldNameLength)]
        public virtual string LookOrFieldName { get; set; }

        public virtual long? SycIdentifierDefinitionId { get; set; }

        [ForeignKey("SycIdentifierDefinitionId")]
        public SycIdentifierDefinition SycIdentifierDefinitionFk { get; set; }

    }
}